apiVersion: apps/v1

kind: Deployment

metadata:

  name: mongo

  labels:

    app: nginx

spec:

  replicas: 1

  selector:

    matchLabels:

      run: mongo

  template:

    metadata:

      labels:

        run: mongo

    spec:

      containers:

      - name: mongo

        image: mongo

        ports:

        - containerPort: 27017




